namespace Tiptopo.Model
{
    public enum PointType
    {
        Point,
        Benchmark,
        SurveyPoint,
        BusSign,
        LampMetal,
        LampStone,
        PostMetal,
        PostSidewalk,
        PostStone,
        TrafficLight,
        TrafficSign,
        Tree,
        TreeConifer,
        Hatchway,
        Grid,
        Bush,
        CablePointer,
        CellTower,
        KilometerSign,
        TrafficPointer,
        LampWood,
        LampDwarf,
        PostWood
    }
}
